'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TranslaTale.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _7zDLL() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7zDLL", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property _7zEXE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7zEXE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property accept_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_left1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_left1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_out() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_out", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_right1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property Aut2exeEXE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Aut2exeEXE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a {&quot;name&quot;:&quot;8BitOperator&quot;,&quot;x_index&quot;:784,&quot;y_index&quot;:4,&quot;max_width&quot;:9,&quot;font&quot;:[{&quot;character&quot;:&quot;g&quot;,&quot;width&quot;:7,&quot;height&quot;:17,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;y&quot;,&quot;width&quot;:7,&quot;height&quot;:17,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;j&quot;,&quot;width&quot;:7,&quot;height&quot;:17,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;q&quot;,&quot;width&quot;:7,&quot;height&quot;:17,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;p&quot;,&quot;width&quot;:7,&quot;height&quot;:17,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;W&quot;,&quot;width&quot;:8,&quot;height&quot;:14,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;%&quot;,&quot;width&quot;:8,&quot;height&quot;:14,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;#&quot;,&quot;width&quot;:8,&quot;height&quot;:14,&quot;cell_width&quot;:8},{ [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property BitOperatorJSON() As String
            Get
                Return ResourceManager.GetString("BitOperatorJSON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property box_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("box_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bricks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bricks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check_box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check_box_uncheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_box_uncheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property check_box1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check_box1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a {&quot;name&quot;:&quot;Comic Sans&quot;,&quot;x_index&quot;:523,&quot;y_index&quot;:263,&quot;max_width&quot;:14,&quot;font&quot;:[{&quot;character&quot;:&quot;Q&quot;,&quot;width&quot;:12,&quot;height&quot;:19,&quot;cell_width&quot;:9},{&quot;character&quot;:&quot;W&quot;,&quot;width&quot;:14,&quot;height&quot;:14,&quot;cell_width&quot;:7},{&quot;character&quot;:&quot;@&quot;,&quot;width&quot;:13,&quot;height&quot;:17,&quot;cell_width&quot;:13},{&quot;character&quot;:&quot;%&quot;,&quot;width&quot;:12,&quot;height&quot;:17,&quot;cell_width&quot;:0},{&quot;character&quot;:&quot;_&quot;,&quot;width&quot;:10,&quot;height&quot;:18,&quot;cell_width&quot;:8},{&quot;character&quot;:&quot;O&quot;,&quot;width&quot;:11,&quot;height&quot;:16,&quot;cell_width&quot;:9},{&quot;character&quot;:&quot;M&quot;,&quot;width&quot;:11,&quot;height&quot;:16,&quot;cell_width&quot;:9},{&quot;character&quot;:&quot;$&quot;,&quot;width&quot;:9,&quot;height&quot;:18,&quot;cell_wi [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property ComicSansJSON() As String
            Get
                Return ResourceManager.GetString("ComicSansJSON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property compare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property compare1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compare1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property compile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross_shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross_shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cross3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property CryptAU3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("CryptAU3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diskette() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diskette", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_button1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_button1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_diff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_diff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_extension_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_extension_png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property file_extension_txt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file_extension_txt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property FileConstantsAU3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("FileConstantsAU3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filter_clear1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filter_clear1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property find1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property find2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_page_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_page_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_page_white1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_page_white1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_page_white2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_page_white2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_colors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font_colors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fonts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fonts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property froggitbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("froggitbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property game_monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("game_monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property gameicon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("gameicon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gear_in() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_in", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property house() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("house", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ico_dwn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_dwn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ico_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ico_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ico_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_8SA_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_8SA_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inbox_document() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inbox_document", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inbox_document_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inbox_document_text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inbox_images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inbox_images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inbox_slide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inbox_slide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inbox_slide1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inbox_slide1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_rhombus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_rhombus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info_rhombus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_rhombus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property layout_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("layout_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property migosp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("migosp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property more_form() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("more_form", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property new_comment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_comment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property next_comment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_comment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_go1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_go1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_green1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_green1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_lightning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_lightning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page_red1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_red1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a {
        '''  &quot;name&quot;: &quot;Papyrus&quot;,
        '''  &quot;x_index&quot;: 784,
        '''  &quot;y_index&quot;: 268,
        '''  &quot;max_width&quot;: 20,
        '''  &quot;font&quot;: [
        '''    {
        '''      &quot;character&quot;: &quot;Q&quot;,
        '''      &quot;width&quot;: 15,
        '''      &quot;height&quot;: 17,
        '''      &quot;cell_width&quot;: 15
        '''    },
        '''    {
        '''      &quot;character&quot;: &quot;A&quot;,
        '''      &quot;width&quot;: 13,
        '''      &quot;height&quot;: 17,
        '''      &quot;cell_width&quot;: 13
        '''    },
        '''    {
        '''      &quot;character&quot;: &quot;O&quot;,
        '''      &quot;width&quot;: 13,
        '''      &quot;height&quot;: 17,
        '''      &quot;cell_width&quot;: 12
        '''    },
        '''    {
        '''      &quot;character&quot;: &quot;W&quot;,
        '''      &quot;width&quot;: 13,
        '''      &quot;height&quot;: 17,
        '''      &quot;cell_width&quot;: 13
        '''     [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property PapyrusJSON() As String
            Get
                Return ResourceManager.GetString("PapyrusJSON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property report_wizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report_wizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property resultset_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resultset_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save_as1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_as1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property star1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property table_select_row() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_select_row", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tablebg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tablebg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_blue_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_blue_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_blue_add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_blue_add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_blue_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_blue_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_blue_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_blue_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag_orange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag_orange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_allcaps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_allcaps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_language() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_language", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_list_numbers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_numbers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_list_numbers1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_numbers1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property time() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("time", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property translation_tool_tip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("translation_tool_tip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ttx24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ttx24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ttxbgbar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ttxbgbar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ttxbgcol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ttxbgcol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ttxbgfooter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ttxbgfooter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property UDTRebuildSFXCAB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UDTRebuildSFXCAB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property UDTSFXCAB_TemplateAU3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UDTSFXCAB_TemplateAU3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property UndertalePatchTool() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UndertalePatchTool", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property UndertalePatchToolbat() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UndertalePatchToolbat", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property UTFontsASCII() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UTFontsASCII", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property WinExtract() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WinExtract", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property WinPack() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("WinPack", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Byte[].
        '''</summary>
        Friend ReadOnly Property xdelta() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("xdelta", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
